### ISSUE TITLE
Can't seem to install

### ISSUE THREAD

**Issue by jonathanKingston** [swc-project/node-swc#23]
With both node-v12.16.1-linux-x64 and node-v13.12.0-linux-x64 I can't seem to get `npm install` or `yarn install` to work.

I get the following errors:
```
npm WARN rm not removing /home/jonathan/debugging/node-swc/node_modules/.bin/semver as it wasn't installed by /home/jonathan/debugging/node-swc/node_modules/semver
npm WARN rm not removing /home/jonathan/debugging/node-swc/node_modules/.bin/json5 as it wasn't installed by /home/jonathan/debugging/node-swc/node_modules/json5
npm WARN rm not removing /home/jonathan/debugging/node-swc/node_modules/.bin/jsesc as it wasn't installed by /home/jonathan/debugging/node-swc/node_modules/jsesc

> microtime@2.1.9 install /home/jonathan/debugging/node-swc/node_modules/microtime
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=13.12.0 runtime=node arch=x64 libc= platform=linux)
make: Entering directory '/home/jonathan/debugging/node-swc/node_modules/microtime/build'
  CXX(target) Release/obj.target/microtime/src/microtime.o
In file included from ../../nan/nan_converters.h:67:0,
                 from ../../nan/nan.h:222,
                 from ../src/microtime.cc:9:
../../nan/nan_converters_43_inl.h: In static member function ‘static Nan::imp::ToFactoryBase<v8::Boolean>::return_t Nan::imp::ToFactory<v8::Boolean>::convert(v8::Local<v8::Value>)’:
../../nan/nan_converters_43_inl.h:18:51: error: no matching function for call to ‘v8::Value::ToBoolean(v8::Local<v8::Context>)’
       val->To ## TYPE(isolate->GetCurrentContext())                            \
                                                   ^
../../nan/nan_converters_43_inl.h:22:1: note: in expansion of macro ‘X’
 X(Boolean)
 ^
In file included from /home/jonathan/.cache/node-gyp/13.12.0/include/node/node.h:67:0,
                 from ../../nan/nan.h:53,
                 from ../src/microtime.cc:9:
/home/jonathan/.cache/node-gyp/13.12.0/include/node/v8.h:2762:18: note: candidate: v8::Local<v8::Boolean> v8::Value::ToBoolean(v8::Isolate*) const
   Local<Boolean> ToBoolean(Isolate* isolate) const;
                  ^~~~~~~~~
/home/jonathan/.cache/node-gyp/13.12.0/include/node/v8.h:2762:18: note:   no known conversion for argument 1 from ‘v8::Local<v8::Context>’ to ‘v8::Isolate*’
In file included from ../../nan/nan_converters.h:67:0,
                 from ../../nan/nan.h:222,
                 from ../src/microtime.cc:9:
../../nan/nan_converters_43_inl.h: In static member function ‘static Nan::imp::ValueFactoryBase<bool>::return_t Nan::imp::ToFactory<bool>::convert(v8::Local<v8::Value>)’:
../../nan/nan_converters_43_inl.h:37:57: error: no matching function for call to ‘v8::Value::BooleanValue(v8::Local<v8::Context>)’
   return val->NAME ## Value(isolate->GetCurrentContext());                     \
                                                         ^
../../nan/nan_converters_43_inl.h:40:1: note: in expansion of macro ‘X’
 X(bool, Boolean)
 ^
In file included from /home/jonathan/.cache/node-gyp/13.12.0/include/node/node.h:67:0,
                 from ../../nan/nan.h:53,
                 from ../src/microtime.cc:9:
/home/jonathan/.cache/node-gyp/13.12.0/include/node/v8.h:2771:8: note: candidate: bool v8::Value::BooleanValue(v8::Isolate*) const
   bool BooleanValue(Isolate* isolate) const;
        ^~~~~~~~~~~~
/home/jonathan/.cache/node-gyp/13.12.0/include/node/v8.h:2771:8: note:   no known conversion for argument 1 from ‘v8::Local<v8::Context>’ to ‘v8::Isolate*’
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:223,
                 from ../src/microtime.cc:9:
../../nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::StringObject>::return_t Nan::imp::Factory<v8::StringObject>::New(v8::Local<v8::String>)’:
../../nan/nan_implementation_12_inl.h:356:37: error: no matching function for call to ‘v8::StringObject::New(v8::Local<v8::String>&)’
   return v8::StringObject::New(value).As<v8::StringObject>();
                                     ^
In file included from /home/jonathan/.cache/node-gyp/13.12.0/include/node/node.h:67:0,
                 from ../../nan/nan.h:53,
                 from ../src/microtime.cc:9:
/home/jonathan/.cache/node-gyp/13.12.0/include/node/v8.h:5688:23: note: candidate: static v8::Local<v8::Value> v8::StringObject::New(v8::Isolate*, v8::Local<v8::String>)
   static Local<Value> New(Isolate* isolate, Local<String> value);
                       ^~~
/home/jonathan/.cache/node-gyp/13.12.0/include/node/v8.h:5688:23: note:   candidate expects 2 arguments, 1 provided
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:223,
                 from ../src/microtime.cc:9:
../../nan/nan_implementation_12_inl.h:356:58: error: expected primary-expression before ‘>’ token
   return v8::StringObject::New(value).As<v8::StringObject>();
                                                          ^
../../nan/nan_implementation_12_inl.h:356:60: error: expected primary-expression before ‘)’ token
   return v8::StringObject::New(value).As<v8::StringObject>();
                                                            ^
In file included from /usr/include/c++/7/cassert:44:0,
                 from /home/jonathan/.cache/node-gyp/13.12.0/include/node/node_object_wrap.h:26,
                 from ../../nan/nan.h:55,
                 from ../src/microtime.cc:9:
../../nan/nan_object_wrap.h: In destructor ‘virtual Nan::ObjectWrap::~ObjectWrap()’:
../../nan/nan_object_wrap.h:24:25: error: ‘class Nan::Persistent<v8::Object>’ has no member named ‘IsNearDeath’
     assert(persistent().IsNearDeath());
                         ^
../../nan/nan_object_wrap.h: In static member function ‘static void Nan::ObjectWrap::WeakCallback(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’:
../../nan/nan_object_wrap.h:127:26: error: ‘class Nan::Persistent<v8::Object>’ has no member named ‘IsNearDeath’
     assert(wrap->handle_.IsNearDeath());
                          ^
../src/microtime.cc: In function ‘void NowStruct(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../src/microtime.cc:75:78: error: no matching function for call to ‘v8::Array::Set(Nan::imp::IntegerFactory<v8::Integer>::return_t, Nan::imp::FactoryBase<v8::Number>::return_t)’
   array->Set(Nan::New<v8::Integer>(0), Nan::New<v8::Number>((double)t.tv_sec));
                                                                              ^
In file included from /home/jonathan/.cache/node-gyp/13.12.0/include/node/node.h:67:0,
                 from ../../nan/nan.h:53,
                 from ../src/microtime.cc:9:
/home/jonathan/.cache/node-gyp/13.12.0/include/node/v8.h:3547:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
/home/jonathan/.cache/node-gyp/13.12.0/include/node/v8.h:3547:37: note:   candidate expects 3 arguments, 2 provided
/home/jonathan/.cache/node-gyp/13.12.0/include/node/v8.h:3550:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^~~
/home/jonathan/.cache/node-gyp/13.12.0/include/node/v8.h:3550:37: note:   candidate expects 3 arguments, 2 provided
../src/microtime.cc:76:79: error: no matching function for call to ‘v8::Array::Set(Nan::imp::IntegerFactory<v8::Integer>::return_t, Nan::imp::FactoryBase<v8::Number>::return_t)’
   array->Set(Nan::New<v8::Integer>(1), Nan::New<v8::Number>((double)t.tv_usec));
                                                                               ^
In file included from /home/jonathan/.cache/node-gyp/13.12.0/include/node/node.h:67:0,
                 from ../../nan/nan.h:53,
                 from ../src/microtime.cc:9:
/home/jonathan/.cache/node-gyp/13.12.0/include/node/v8.h:3547:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
/home/jonathan/.cache/node-gyp/13.12.0/include/node/v8.h:3547:37: note:   candidate expects 3 arguments, 2 provided
/home/jonathan/.cache/node-gyp/13.12.0/include/node/v8.h:3550:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^~~
/home/jonathan/.cache/node-gyp/13.12.0/include/node/v8.h:3550:37: note:   candidate expects 3 arguments, 2 provided
microtime.target.mk:111: recipe for target 'Release/obj.target/microtime/src/microtime.o' failed
make: *** [Release/obj.target/microtime/src/microtime.o] Error 1
make: Leaving directory '/home/jonathan/debugging/node-swc/node_modules/microtime/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/jonathan/Software/node-v13.12.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.3.0-42-generic
gyp ERR! command "/home/jonathan/Software/node-v13.12.0-linux-x64/bin/node" "/home/jonathan/Software/node-v13.12.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/jonathan/debugging/node-swc/node_modules/microtime
gyp ERR! node -v v13.12.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! microtime@2.1.9 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the microtime@2.1.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jonathan/.npm/_logs/2020-04-05T12_34_19_283Z-debug.log
```

Removing `bench-runner` from the devDependencies fixes this issue.

However I get the following:
```
> @swc/core@1.1.38 prepublish /home/jonathan/debugging/node-swc
> tsc -d

src/index.ts:13:16 - error TS2580: Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i @types/node`.

13 const native = require("./native");
                  ~~~~~~~

src/index.ts:18:24 - error TS2580: Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i @types/node`.

18 export const version = require("./package.json").version;
                          ~~~~~~~

src/util.ts:96:1 - error TS2580: Cannot find name 'module'. Do you need to install type definitions for node? Try `npm i @types/node`.

96 module.exports = {
   ~~~~~~


Found 3 errors.
```

Installing this dependency gets it installed.

**Comment by kdy1** [comment]
The first error seems like a one from `microtime`, not swc.

**Comment by jonathanKingston** [comment]
Hmm this seems to all work if I use: `./scripts/ci/linux/build.sh` is that normally how you build it?

**Comment by kdy1** [comment]
@jonathanKingston Yes, the ci invokes the script in the docker

**Comment by jonathanKingston** [comment]
I guess I was looking for the suggested way that you'd build this locally to test changes in swc (I have a bug it seems with `require` always in the node output). In my project I'm using `const swc = require("@swc/core");` I'm hoping I can just fix a bug but I'm struggling to build.

I built the code but then including it via `npm link` to my project or directly to the native output.

Any advice would be really great.

**Comment by jonathanKingston** [comment]
Huh all of a sudden it now works! I'm guessing it was a dependency order or something perhaps?
I'm going to close this as I don't really know the order that fixed it, feel free to re-open etc.
